### PR TITLE
XML.xsdCheck not working: add get list of issues

### LINKED ISSUE #15: XML.xsdCheck not working
# Summary
Referring to https://support.xillio.com/helpdesk/tickets/1933, fix this madness.
Additional feature:
The xsd check construct will get an optional parameter "outputAsList"; if the default "false" is used the construct will return true if and only if the xml is not valid, if the parameter is "ftrue" then the construct will return a list of validation issues.

### PR DESCRIPTION
**Pull request by andrea-parrilli**
Summary

Added a parameter to the xsdCheck construct to return the list of issues without logging them. Defaults to previous behavior so this should be backwards compatible.

NOTE: this PR contains only the additional feature described above. The fix for the bug has already been merged previously. The issue has been reopened to request the feature described above.

Fix #15

### CODE REVIEW

File: plugin-xml/src/test/java/nl/xillio/xill/plugins/xml/constructs/XsdCheckConstructTest.java [hunk 1]
```diff
@@ -58,12 +58,12 @@ public void testProcess() {
         when(xsdService.xsdCheck(any(), any(), any())).thenReturn(true);
 
         // Run
-        MetaExpression result = XsdCheckConstruct.process(context, xsdFilenameVar, xmlFilenameVar, xsdService, logger);
+        MetaExpression result = XsdCheckConstruct.process(context, xsdFilenameVar, xmlFilenameVar, fromValue(false), xsdService, logger);
```
Comment (Konijnendijk) [inline plugin-xml/src/test/java/nl/xillio/xill/plugins/xml/constructs/XsdCheckConstructTest.java]: To be really complete, add a test here too for the `outputAsList=true` case
